apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-rest-api
  labels:
    app: rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest
  template:
    metadata:
      labels:
        app: rest
    spec:
      containers:
      - name: hello-world-rest-api
        image: lgutierrezfarinas/hello-world-rest-api:latest
        ports:
          - containerPort: 8080
