name: Commit Stage
run-name: Performing commit stage script
on:
  pull_request:
    types: [opened]
jobs:
  commit-stage:
    runs-on: eclipse-temurin:11
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: bash commit-stage.sh
