name: Commit Stage
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  commit-stage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: bash hello-world-rest-api.sh
