name: Merge to main branch
run-name: Performing merge to main branch
on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  merge-to-main-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: bash merge-to-main.sh
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: lgutierrezfarinas/hello-world-rest-api:latest
      - name: Update kubernetes deployment
        uses: redhat-actions/oc-login@v1
        env:
          OPENSHIFT_NAMESPACE: l-gutierrez-dev
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
      - run: bash deploy-kubernetes.sh